# Generated by Django 5.1.5 on 2025-06-01 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
